name: 'Setup dimtensor'
description: 'Setup Python and install dimtensor with dependencies'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  install-extras:
    description: 'Extra dependencies to install (comma-separated, e.g., "torch,jax,dev")'
    required: false
    default: 'dev'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

outputs:
  python-version:
    description: 'Python version that was installed'
    value: ${{ steps.setup-python.outputs.python-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-py${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-pip-py${{ inputs.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dimtensor
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "pyproject.toml" ]; then
          # Installing from local repository
          if [ -n "${{ inputs.install-extras }}" ]; then
            pip install -e ".[${{ inputs.install-extras }}]"
          else
            pip install -e .
          fi
        else
          # Installing from PyPI
          if [ -n "${{ inputs.install-extras }}" ]; then
            pip install "dimtensor[${{ inputs.install-extras }}]"
          else
            pip install dimtensor
          fi
        fi

    - name: Verify NumPy version
      shell: bash
      run: |
        python -c "import numpy; print(f'NumPy: {numpy.__version__}'); assert int(numpy.__version__.split('.')[0]) < 2, 'NumPy 2.x not supported'"

    - name: Show installed packages
      shell: bash
      run: |
        pip list | grep -E "dimtensor|numpy|torch|jax"
